### ISSUE TITLE
plugin not finding hibp file

### ISSUE THREAD

**Issue by davald** [mihaifm/HIBPOfflineCheck#1]
get message HIBP file not found but confirmed file downloaded and in correct folder.

**Comment by mihaifm** [comment]
This happened to me once while testing the plugin but I can't remember what was the scenario.

Can you provide the info below:
* Are you using the .plgx or compiled the dll ?
* Can you confirm that the file name is "pwned-passwords-ordered-2.0" ?
* Are you using KeePass installation or the portable version ?

**Comment by mihaifm** [comment]
Indeed there was a problem with loading the HIBP file, when using the installed version of KeePass. Thanks for pointing this out.

**Comment by mihaifm** [comment]
weird...perhaps try to clear the plugin cache? or try the portable version of KeePass?

**Comment by davald** [comment]
clearing the cache didn't help.  any other ideas?  thanks for being
responsive on this.

**Comment by mihaifm** [comment]
thanks for testing this as well...we need to get to the bottom of this :)

can you let me know which system are you using, and where did you install KeePass ?
could be some file permission thing, not sure.

thanks

**Comment by mihaifm** [comment]
Just tried on a fresh system, Windows 10 64 bit, installed KeePass on the default location `C:\Program Files (x86)\KeePass Password Safe 2`, placed the HIBP file in the same location...and it worked for me :(

**Comment by davald** [comment]
I have
Operating System
Windows 10 Home 64-bit

KeePass Password Safe 2.38 Dominik Reichl 2/11/2018 7.66 MB 2.38 All users
installed at

C:\Program Files (x86)\KeePass Password Safe 2

​hibp file same location

​
pwned-passwords-2.0.txt

​plugin HIBPOfflineCheck.plgx v1.1.0.0 installed in ​
C:\Program Files (x86)\KeePass Password Safe 2\Plugins

I am an administrative user and the folder and file looks correct for that.

​Could the hibp file be bad?

**Comment by mihaifm** [comment]
I think you got the HIBP file ordered by prelevance, which will not work. You should get the one ordered by hash, from here https://haveibeenpwned.com/Passwords

File name should be *pwned-passwords-ordered-2.0.txt*, after extracting the archive.

This is needed by the plugin for fast searching, I will try to make it clearer in the readme.

**Comment by mihaifm** [comment]
Clarified readme: https://github.com/mihaifm/HIBPOfflineCheck/commit/6cf38fb4cfc7a58dc1688e2ec9b52c856a61cd26
