### ISSUE TITLE
[Feature request] make pwned-passwords-ordered file location configurable

### ISSUE THREAD

**Issue by baloan** [mihaifm/HIBPOfflineCheck#11]
I prefer to store the file in a location different from the progam files. I consider recompiling the plugin with a hardcoded filepath - but I realise that is a bad idea. Unfortunately I am not "fluent" in C# to implement and create a pull request.

**Comment by baloan** [comment]
Apologies, dup of #3

**Comment by mihaifm** [comment]
I plan to implement a customization screen, but in the meantime you could use Keepass portable.
https://keepass.info/download.html

**Comment by baloan** [comment]
For the time being I hardcoded the filepath - works fine.

**Comment by mihaifm** [comment]
Feature request implemented: 146106f15d71b2d65b4c1d795db3849fc6ae787f  
Can you help verifying if it works?

**Comment by baloan** [comment]
Works as designed. Splendid.
