### ISSUE TITLE
Support a bloom filter version of the HIBP list

### ISSUE THREAD

**Issue by Caligatio** [mihaifm/HIBPOfflineCheck#19]
I recently stumbled onto this plugin and was super excited about it until I realized the storage requirements for the HIBP list.  Have you looked into supporting some sort of [bloom filter](https://en.wikipedia.org/wiki/Bloom_filter) version of the HIBP list?  I am certainly [not ](https://www.bloomingpassword.fun/) [the ](https://gist.github.com/marcan/23e1ec416bf884dcd7f0e635ce5f2724) [first ](http://detect-respond.blogspot.com/2018/05/enhancing-enhanced-privacy-checking.html) [person ](https://gist.github.com/JohnTroony/6e5788789c0522ed726f045bf6d6299e) to think about doing this but, if your plugin supported it, this could be the first implementation that was actually usable.

I'm happy to try to help!

Quick Edit: You would lose the password count but gain like a 30x storage savings plus potentially a faster lookup.

**Comment by mihaifm** [comment]
Thanks for the suggestion, interesting idea. I'll look into it.

**Comment by Caligatio** [comment]
I have some fun ideas how to distribute a possible bloom filter version of HIBP via IPFS+Cloudflare and I'm also happy to produce the actual filter output if it's helpful.

**Comment by mihaifm** [comment]
I'm thinking to add a button in the options to calculate the bloom filter locally, it shouldn't be too difficult.

**Comment by mihaifm** [comment]
Hi

It took a while to implement your suggestion, but I finally managed to get something working. Check out the new release, and maybe help test it if you have the time.

You can generate the filter from the plugin settings. It doesn't take too long to generate it, I tested this on 2 systems:
* older i7 2600k with HDD storage: 40 minutes
* i7 6770HQ with SSD: 15 minutes

**Comment by Caligatio** [comment]
Just tried it out and it appears to work!  24x space savings isn't too bad at all :)

**Comment by mihaifm** [comment]
Great, thanks a lot!
