### ISSUE TITLE
Entry made by Keepass HTTP Plugin lets crash HIBPOfflineCheck

### ISSUE THREAD

**Issue by ventilator** [mihaifm/HIBPOfflineCheck#21]
[crashy.zip](https://github.com/mihaifm/HIBPOfflineCheck/files/2799299/crashy.zip)

If you use this (almost) empty Keepass Database (password "test") and try to execute the plugin on the entry "KeePass HTTP Settings" an exception occurs:
![image](https://user-images.githubusercontent.com/4276067/51790809-43f01b00-219a-11e9-8bbe-6896056e97e9.png)

**Comment by jeff9315** [comment]
I can verify that this occurs. It APPEARS that certain plugins create an entry for themselves in which the password LOOKS blank but probably contains an unprintable character. Just typing in one character and then backspacing to blank it out seems to fix the issue (as as workaround).

**Comment by mihaifm** [comment]
Thanks for the info and crashy database, indeed there was a problem there. I'll just close the issue since it's the same as #17 , see my comments there.
