### ISSUE TITLE
New Entries not checked

### ISSUE THREAD

**Issue by p-doyle** [mihaifm/HIBPOfflineCheck#25]
I am not sure if it is supposed to but I noticed that, when initially creating a new entry, the HIBP check is not run.  It does work when I go back to edit the entry, even if I don't change the password(not too concerned with that though)

I think it would be nice if the check could be run when an entry is first created, if that is possible.

Thanks for all your work on this!

**Comment by mihaifm** [comment]
I'm looking for a solution for this, the problem is that KeePass doesn't raise an event when a new password is created. There is only a `Touched` event fired when an entry is edited.

**Comment by mihaifm** [comment]
This issue is finally fixed. After some time using the plugin it became apparent that it's a must have.
It should be available at the next release.
Cheers!
