### ISSUE TITLE
Set Alternate Location for Password File

### ISSUE THREAD

**Issue by thatguy9129** [mihaifm/HIBPOfflineCheck#3]
I'd like the ability to set an alternate location for the offline password file. I don't have enough storage on my primary drive to house that file, so I placed it elsewhere.

**Comment by mihaifm** [comment]
Ok, I’ll give this a thought. I would probably need to add a location in the settings where you would input the path. Need to check if something similar has been done for other plugins.

**Comment by mihaifm** [comment]
Implemented a config screen under `Tools->HIBP Offline Check` that allows setting the file location. Please help verifying the functionality.

**Comment by homes32** [comment]
> 
> 
> Implemented a config screen under `Tools->HIBP Offline Check` that allows setting the file location. Please help verifying the functionality.

working here. thanks for the addition!
