### ISSUE TITLE
Feature request: offline only

### ISSUE THREAD

**Issue by chabis0815** [mihaifm/HIBPOfflineCheck#30]
Hello,

First of all: thank you very much for this useful tool! 
I would like to install it on the client computers at my work, but I am a little bit concerned about the online-check and would appreciate it, if I can restrict the plugin only to do a "offline scan".
Our users have no write-permissions in the KeePass folder on the clients, but the configuration is saved in %APPDATA%, so there seems to be no way to permanently disable the online scan.
I really would appreciate a solution to restrict the check to an offline file.
Thank you and greetings from Germany,
Christian

**Comment by chabis0815** [comment]
Sorry, saw that this (maybe) can be fixed with KeePass and its "enforced" configuration file itself - closing this issue.

**Comment by mihaifm** [comment]
Ok, cool. You can also use the older 1.3.2 release which doesn’t have online mode.

**Comment by chabis0815** [comment]
Thanks for your reply -actually the enforced configuration seems not to work with (your?) custom entries ... So I guess I will use the older version.
Still very useful tool -thanks a lot!
