### ISSUE TITLE
HIBP API error

### ISSUE THREAD

**Issue by dusscloud** [mihaifm/HIBPOfflineCheck#31]
I am trying to use HIPB online.
I successfully used it on a windows desktop, but on my ubuntu I get "HIBP API error" (with latest 1.4.1 version). 
I can access https://api.pwnedpasswords.com/range/ABCDE with my browser
What could be wrong?

**Comment by mihaifm** [comment]
It may be due to proxy settings. On Windows it should use system proxy but I'm not sure about linux. Are you behind a proxy?

**Comment by dusscloud** [comment]
no proxy at all

**Comment by mihaifm** [comment]
It could be a TLS issue if you're running an older Mono version. pwnedpasswords.com requires TLS 1.2 which was added in Mono 4.8, as far as I can see:

https://www.mono-project.com/docs/about-mono/releases/4.8.0/#tls-12-support

I'm not encountering any problems on Ubuntu so this is a bit difficult to debug.

**Comment by dusscloud** [comment]
$ mono --version
Mono JIT compiler version 4.6.2 (Debian 4.6.2.7+dfsg-1ubuntu1)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	LLVM:          supported, not enabled.
	GC:            sgen

what's yours?

**Comment by mihaifm** [comment]
$ mono --version
    Mono JIT compiler version 5.18.0.240 (tarball Wed Jan 16 09:10:16 UTC 2019)
    Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
            TLS:           __thread
            SIGSEGV:       altstack
            Notifications: epoll
            Architecture:  amd64
            Disabled:      none
            Misc:          softdebug
            Interpreter:   yes
            LLVM:          yes(600)
            Suspend:       preemptive
            GC:            sgen (concurrent by default)

I think you might need a mono update.

**Comment by boldt** [comment]
I had the same issue and I can confirm, that a newer mono version fixed that issue:

$ mono --version | grep version
Mono JIT compiler version 4.6.2 (Debian 4.6.2.7+dfsg-1ubuntu1)

```
sudo apt install gnupg ca-certificates
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
echo "deb https://download.mono-project.com/repo/ubuntu stable-bionic main" | sudo tee /etc/apt/sources.list.d/mono-official-stable.list

sudo apt update
sudo apt upgrade
```

* From https://www.mono-project.com/download/stable/

**Comment by mihaifm** [comment]
@boldt thanks for the confirmation, I'll just add a release note mentioning the required Mono version
