### ISSUE TITLE
KeePass 2.42.1 no such menu item "Selected Entries" hence not possible to selectively check records

### ISSUE THREAD

**Issue by aniro** [mihaifm/HIBPOfflineCheck#34]
The following is not doable in the most recent KeePass 2.42.1:
> Select multiple entries, right click -> Selected Entries -> Have I been pwned?

In 2.41 there was `Selected Entries` context menu item, but in 2.42.1 it is not available.
Not sure whether it is bug in KeePass or they intentionally removed it. In either case it is now impossible to check records individually in HIBP

**Comment by mihaifm** [comment]
Weird, I don't see any reference to this in the release notes, although there are some changes related to the context menu. I'll see if I can update the plugin.

**Comment by mihaifm** [comment]
I published a new release to fix the issue.

You can now find the options directly under the right click menu, or using the Entry section in the main menu.
