### ISSUE TITLE
HIBP EXCLUDE value reverts back to previous values when Saving the Keepass data

### ISSUE THREAD

**Issue by jeff9315** [mihaifm/HIBPOfflineCheck#37]
Hmmm ... Using the new "Exclude" Option that you just introduced ... Everything works fine until I do a Save. Then the "Exclude" gets reset back to the number of breaches.

I wonder if it's the same type of issue that got fixed that I reported in https://github.com/mihaifm/HIBPOfflineCheck/issues/15 which was fixed.

The sequence of steps is:
* I right-click an entry
* Select HIBP > Exclude (or even Clear). 
* It says "Excluded". 
* Then I hit Save. 
* Then I look at the entry and it shows the number of breaches instead of "Excluded".

Note that I have a Synchronize with 2 other databases.

**Comment by mihaifm** [comment]
Ok, doesn't happen to me, but seems similar to https://github.com/mihaifm/HIBPOfflineCheck/issues/15
I'll check.

**Comment by mihaifm** [comment]
I've pushed a fix for this (with some additional changes to improve performance when checking a lot of passwords). Can you check it with the attached plgx (or compile from source).

[HIBPOfflineCheck.zip](https://github.com/mihaifm/HIBPOfflineCheck/files/3639032/HIBPOfflineCheck.zip)

**Comment by jeff9315** [comment]
Yep ... Works perfectly. THANKS!!!!!

**Comment by mihaifm** [comment]
Released in the new version. Cheers!
