### ISSUE TITLE
KeePass update check claims v1.7.1 is available

### ISSUE THREAD

**Issue by Caligatio** [mihaifm/HIBPOfflineCheck#38]
On launch, KeePass pops up a warning telling me to upgrade my current HIBPOfflineCheck from v1.7.0 to v1.7.1 but there is no v1.7.1 available in this repository.  It appears that [version.txt](/mihaifm/HIBPOfflineCheck/blob/master/version.txt) reflects this incorrect version.

**Comment by mihaifm** [comment]
Yea, I commited that file, I’m planning to release some bug fixes, but the’re not done yet. I forgot KeePass reads the file from Github  to check version. Let me just revert that until the new version is released.

**Comment by mihaifm** [comment]
Done, thanks for pointing it out. I don't have automatic update check so I wouldn't have noticed this.

**Comment by Caligatio** [comment]
NP, probably the easiest bug to squash :)
