### ISSUE TITLE
Support for HIBP v3 files

### ISSUE THREAD

**Issue by hharsunen** [mihaifm/HIBPOfflineCheck#4]
I assume file would be the ```(ordered by hash)``` one, which name is ```pwned-passwords-ordered-by-hash.txt```?

**Comment by mihaifm** [comment]
yes, v3 should be supported, I haven’t tried yet but from what I see the format is the same.

Let me know if there are any issues.

**Comment by hharsunen** [comment]
works if you rename the file to ```pwned-passwords-ordered-2.0.txt```, should you update the README or make it so that plugin reads both v2 file and v3 automatically, uses newest if available?

**Comment by hharsunen** [comment]
I don't have v2 file downloaded so I can't verify that.

**Comment by mihaifm** [comment]
There was a small issue where it didn't load the V3 file correctly if the 7z archive was also present in the folder (it was reading the 7z file first). I corrected that, also added some logic to use the newest file if both V2 and V3 are present.
