### ISSUE TITLE
The progress window for online checks gets lost

### ISSUE THREAD

**Issue by mlaily** [mihaifm/HIBPOfflineCheck#42]
Hello,

I'm not sure the title is very clear, so I will explain:

The progress window when doing an online check does not show in the Windows task bar, and is not modal, so if the progress window loses focus (because the user is doing something else), it's hard to find it back!

Making it modal is probably not a very good idea, since it would prevent the use of KeePass while the online check is in progress.

I think the easiest way to fix that would be to make the progress window show in the Windows task bar. It's currently explicitly set to false, but I'm not sure why...

**Comment by mihaifm** [comment]
Ok, I see your point. I'll try to fix it.

**Comment by mihaifm** [comment]
Fixed (5f2bd7ea2775a141fd159ba21633c7135665e28c) and released in a new version.
Thanks for pointing this out and for suggesting the fix.

**Comment by mlaily** [comment]
Thank *you*!
