### ISSUE TITLE
[FR] Add reporting

### ISSUE THREAD

**Issue by tbennett6421** [mihaifm/HIBPOfflineCheck#43]
Would it be possible to add a entry under the Find menu to generate a report of entries that have been pwned? It would be nice to have a list of things that need to be addressed in a large password vault.

I mean I can find by password or look for identical features, but I can see that being a useful feature if feasible

**Comment by mihaifm** [comment]
Thanks for the suggestion, I will try to find a solution.

You can currently do a Search for all (just press Enter in the Search box) and then order by the "Have I been pwned" column. The problem with this approach is that it groups them by folder, so even if you order by the column you don't get all the pwned passwords at the top.

Your suggestion is better but I need to check if it's possible to implement.

**Comment by strarsis** [comment]
+1, and a warning with summary, similar to what Google Chrome does for hacked passwords.

**Comment by mihaifm** [comment]
Feature implemented: https://github.com/mihaifm/HIBPOfflineCheck/commit/8ff8db61cb9287fc66180ca40ecaacf0d40c128e

Check the latest release. 

Sorry it took so long, not much time these days.
