### ISSUE TITLE
1.7.5 is awesome ... and a feature request

### ISSUE THREAD

**Issue by jeff9315** [mihaifm/HIBPOfflineCheck#44]
1.7.5 is an awesome change. Previously I had to go through some small contortions to see that same information. THANK YOU!!!

Now, one small tweak to that would be an option to exclude entries in the Recycle Bin ... and maybe even exclude expired entries as a 2nd option.

THANK YOU SO MUCH!!!!!!!! Jeff

**Comment by mihaifm** [comment]
Sounds like a reasonable improvement, I will try to implement it.

**Comment by mihaifm** [comment]
I've added two new options to exclude recycle bin and expired entries. Can you test this with the attached .plgx? It's the same file I'll be uploading to the releases.
[HIBPOfflineCheck.zip](https://github.com/mihaifm/HIBPOfflineCheck/files/6988908/HIBPOfflineCheck.zip)

**Comment by jeff9315** [comment]
Thanks .... 

The **Exclude Expired** option works PERFECTLY. The **Exclude Recycle Bin** would be better if it also excluded subfolders within the recycle bin. Other than that, it looks really good.

**Comment by mihaifm** [comment]
Well spotted, I corrected the Recycle Bin logic, can you try again, file attached below. Thanks for taking the time to test it.

[HIBPOfflineCheck.zip](https://github.com/mihaifm/HIBPOfflineCheck/files/7008341/HIBPOfflineCheck.zip)

**Comment by jeff9315** [comment]
PERFECT!!!!!!

**Comment by mihaifm** [comment]
That's great, release 1.7.6 published. 

cheers
