### ISSUE TITLE
Shows warning message during favicon download

### ISSUE THREAD

**Issue by strarsis** [mihaifm/HIBPOfflineCheck#45]
For automatically downloading and assigning favicons from the URL saved in the password entries, 
I use the KeePass [Yet Another Favicon Downloader](https://github.com/navossoc/KeePass-Yet-Another-Favicon-Downloader) plugin.
When that favicon plugin finished, I get the HIBPOfflineCheck warning messages, as I would if had saved the entries manually.
I suspect a hook is used by HIBPOfflineCheck warnings for entries being modified. Can this be skipped when an automated tool like the favicon plugin modifies the entries?

**Comment by mihaifm** [comment]
I can look into it but in the mean time you can deactivate the warning from the plugin options. I suppose it’s a bit tedious since you’d have to toggle it every time you dow load favocons.

**Comment by cristianst85** [comment]
There are two aspects to this.

1) One could argue that the `Display warning message after editing insecure passwords` does too much (i.e., it also shows the warning when you edit any other field beyond the password field which is not what the description implies).

2) If we change the behavior to only show the warning when the password field is edited, it will also solve the issue described by @strarsis.

The tricky part is to detected if the password field was edited or not. I think this might be possible by looking at the entry's history and taking the previous version and comparing the password field with the current one.

@mihaifm, any thoughts on this?

**Comment by cristianst85** [comment]
The only limiting scenario will be when _Limit number of history items per entry_ (`File` -> `Database Settings...`) is set to `0` (i.e., the entry will not have any history), but in that case, we could show the warning regardless.

**Comment by mihaifm** [comment]
I agree with this in principle, we should show the warning only after the password changes, not the entire entry. I'll take a look at this history approach, it looks promising.

**Comment by mihaifm** [comment]
This is fixed now, thanks @cristianst85 for the solution, worked perfectly.
