### ISSUE TITLE
Offline check mode has no effect. Always results in Secure, even for known breached entries.

### ISSUE THREAD

**Issue by reclaimer5146** [mihaifm/HIBPOfflineCheck#58]
Duplicate of #48 but for offline mode.

Used the password downloader referenced in HIBP. Created a ~10gb file.
Pointed the plugin at the offline file. All passwords are coming back secure, even known breached ones.

KeePass 2.53
HIBPOfflineCheck 1.7.9
MD5Sum of Offline passwords: 406CD8758AB00D597B9F350DC10C2FAF

**Comment by cristianst85** [comment]
Which password file have you downloaded?

> The required file is the one with format SHA-1 (ordered by hash). 

The `pwned-passwords-sha1-ordered-by-hash-v8.txt` has about 34.7 GB.

**Comment by cristianst85** [comment]
The `pwned-passwords-sha1-ordered-by-hash-v8.7z` has ~ 15.6 GB, but you need to un-zip it first to use it! 

![image](https://user-images.githubusercontent.com/12585988/211893652-d0b86d8b-0f43-4755-bf15-1e5c61044583.png)
