### ISSUE TITLE
Big mess on Uninstall

### ISSUE THREAD

**Issue by PhilZ-cwm6** [mihaifm/HIBPOfflineCheck#6]
Many thanks for this plugin.

However, it was not nuilt in mind with a proper uninstall.
It will leave a string field on each tested entry.

Since Keypass doesn't provide a proper way to remove string fields for many entries, only using some tools like KPEnhancedEntryView can automate the job.

I think an alternative way should be found so that the plugin displays the status without forcing to save the values

**Comment by mihaifm** [comment]
Yes, the the strings are stored in the database and indeed it's not easy to remove them. The column is a custom field, you can hide it, but if you really want to get rid of those entries you could export the database as xml and use an xpath/xslt tool to remove them.

**Comment by mihaifm** [comment]
Here's the xslt I used to remove the string values:

`<?xml version="1.0" encoding="utf-8"?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" >
    <xsl:template match="@*|node()">
        <xsl:copy>
            <xsl:apply-templates select="@*|node()"/>
        </xsl:copy>
    </xsl:template>
    <xsl:template match="String[Key[contains(text(), 'Have I been pwned?')]]"/>
</xsl:stylesheet>`

**Comment by homes32** [comment]
[KPFieldsAdminConsole](https://keepass.info/plugins.html#kpfieldsadmin) is another option for point & click bulk delete if your not comfy with xslt.

**Comment by mihaifm** [comment]
Added a right click option to delete the new string entries from checked passwords.

`right click -> Selected Entries -> Clear pwned status`

This should help you keep the database nice and clean in case you want to uninstall the plugin.

146106f15d71b2d65b4c1d795db3849fc6ae787f

**Comment by PhilZ-cwm6** [comment]
thanks :-)
