### ISSUE TITLE
Generating Bloom Filter results in Error

### ISSUE THREAD

**Issue by Stray216** [mihaifm/HIBPOfflineCheck#60]
I'm getting an error message when trying to generate the bloom filter.
Here's a timeline of my research so far:

The error message I'm getting looks like this:
[https://pastebin.com/MwkdBKzt](https://pastebin.com/MwkdBKzt)

After asking ChatGPT about this, this was its first response: 
[https://pastebin.com/gC3wP0r2](https://pastebin.com/gC3wP0r2)

I pasted the whole of the BloomWorker() method in CreateBloomFilter.cs to ChatGPT and its response was this:
[https://pastebin.com/pqMYKhF7](https://pastebin.com/pqMYKhF7)

I figured there must be lines shorter than 40 in the pwned passwords text file, so I had ChatGPT write me a python script to search for these. The output in the console was this:
[https://pastebin.com/N2SzUijC](https://pastebin.com/N2SzUijC)

Then I asked ChatGPT if line 124 could be modified so that it splits the line at the ":" symbol rather than taking the first 40 characters. Its response was this:
[https://pastebin.com/LjneGxfC](https://pastebin.com/LjneGxfC)

I hope any of this is helpful. I really want this bloom filter file as 34,9GB is really large.

**Comment by mihaifm** [comment]
Hi, interesting analysis :)
Are you sure you have the correct input file? SHA1 hashes are always 40 characters so not sure why are you finding so many that aren't size 40.

**Comment by cristianst85** [comment]
@Stray216, can you describe what (and how) exactly you are trying to do?

Also, you might want to read https://github.com/mihaifm/HIBPOfflineCheck/issues/58.

**Comment by Stray216** [comment]
> @Stray216, can you describe what exactly you are trying to do? And how (step by step)?

I am trying to get the bloom filter file by using the generator from this plugin.
I click on the generate button and specify the pwned_passwords file and the output bloom filter file.
When the generator is running I get this error: [https://pastebin.com/MwkdBKzt](https://pastebin.com/MwkdBKzt)

While I can choose to ignore the error message, the bloom filter won't generate any further after it.

> Also, you might want to read https://github.com/mihaifm/HIBPOfflineCheck/issues/58 (start from the end).

I've read it and don't see how it can help me. If you know how this can help me, do tell. :D

**Comment by cristianst85** [comment]
What's your input file?
How did you obtain it?
What's the exact file size (in bytes)?
Can you try to re-download it? (create an MD5 hash sum first for the one you have, then compare it with the MD5 of the re-downloaded file, if the file sizes do not match, then ignore this)

I am assuming your input file is/was botched during the download.

**Comment by Stray216** [comment]
With the help of [troyhunt](https://github.com/troyhunt) and [stebet](https://github.com/stebet) from the [PwnedPasswordsDownloader](https://github.com/HaveIBeenPwned/PwnedPasswordsDownloader), I was able to download a, seemingly uncorrupted, pwned passwords file that has no lines shorther than 40 characters.

I will attempt to generate the bloom filter tomorrow evening.

**Comment by mihaifm** [comment]
I uploaded the latest bloom filter to the [HIBPBloomFilter](https://github.com/mihaifm/HIBPBloomFilter/releases) repository, feel free to download it from there.

I saw the issue you raised on [PwnedPasswordsDownloader](https://github.com/HaveIBeenPwned/PwnedPasswordsDownloader), indeed it seems like the input file had some wrong entries which were corrected. Nice job on figuring this out.

**Comment by Stray216** [comment]
I successfully generated the bloom filter without any errors.
I tested the plugin with a few good/bad passwords using the bloom filter and everything seems to work fine.
Thank you also for the new release at the HIBPBloomFilter repository.
