### ISSUE TITLE
HIBP doesn't have a Text option in Version 3

### ISSUE THREAD

**Issue by jeff9315** [mihaifm/HIBPOfflineCheck#7]
In the latest version of Have I Been Pwned (V3) ([https://haveibeenpwned.com/Passwords](https://haveibeenpwned.com/Passwords)), there's no text option. Just By Hash and By Prevalence. I'm not sure if By Hash is what you want or not.

**Comment by mihaifm** [comment]
you need the one ordered by hash

**Comment by mihaifm** [comment]
Please check the updated readme for instructions, V3 files should work properly, just download the -ordered-by-hash file
