### ISSUE TITLE
[1.2.0] signature and version mismatch

### ISSUE THREAD

**Issue by baloan** [mihaifm/HIBPOfflineCheck#8]
The latest release binary 1. signature does not verify for me, and 2. shows the wrong version number. Is this a genuine release?

![image](https://user-images.githubusercontent.com/651799/46255701-d522df80-c48f-11e8-90a8-491db7baa96b.png)
![image](https://user-images.githubusercontent.com/651799/46255709-e9ff7300-c48f-11e8-9c87-1d57d6b05016.png)
```
File: HIBPOfflineCheck.plgx
  CRC-32: aea092c2
   SHA-1: 6c81744213f254088ff238665de2f19450316c4d
 SHA-256: df2e7bca755b81b328cd0f19c20ab40ccd76a5809be74d8cd3bd918bbd6af1d4
 SHA-512: 9a489be4439033da807a229eab92a2f9a13097aa7e8efa92b643d03ceb7cb5767e46f48b70b01d07e777d95b3a3e7671ea14928d2f0e6a0ff2b30e259c53cc2e


```

**Comment by mihaifm** [comment]
Weird, signature should verify, did you import my key from `Util/' ?....I'll try it tonight on a fresh system that doesn't have my signature.
Version number is a display issue, I'll correct it tonight.

**Comment by mihaifm** [comment]
Updated the version number and uploaded a new binary with a signature. You can use the below commands to check the signature, but Kleopatra should work as well.

    curl https://raw.githubusercontent.com/mihaifm/HIBPOfflineCheck/master/Util/mihaifm.asc | gpg --import
     gpg --verify HIBPOfflineCheck.plgx.asc HIBPOfflineCheck.plgx

Could you help with checking this?

**Comment by jeff9315** [comment]
The version number now matches.  I didn't check the signature (I don't have anything to do that on Windows).

**Comment by baloan** [comment]
Now works as designed.
![image](https://user-images.githubusercontent.com/651799/46366250-166ee700-c66a-11e8-92ef-4a65cbb63242.png)

**Comment by mihaifm** [comment]
@baloan cool, thanks.
