### ISSUE TITLE
Minor documentation error and feature request

### ISSUE THREAD

**Issue by jeff9315** [mihaifm/HIBPOfflineCheck#9]
This works REALLY well and FAST. One very minor issue ...

In the docs, you say ... Double clicking the "Have I been pwned?" column for any entry will display the password status. Editing an entry will clear the status.

I suspect double-clicking it rechecks it and updates it too fast to be noticed. And there's no way to actually clear the status ... which brings me to a suggested enhancement. It would be nice to be able to clear out all the statuses so you can rerun it after downloading a new HIBP hashed file and verify that everything has been rechecked.

THANKS Jeff !!!

**Comment by mihaifm** [comment]
Thanks, I'll correct the readme, indeed when double clicking it rechecks and displays the same status. 

I can probably implement another right click option to clear the status, which would take care of #6 as well...thanks for the suggestion.

**Comment by mihaifm** [comment]
Feature request implemented: 146106f15d71b2d65b4c1d795db3849fc6ae787f

`right click -> Selected Entries -> Clear pwned status`

Can you help verifying it?

**Comment by jeff9315** [comment]
Perfect!!!!
